name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Create constants.ts
        run: |
          cat > src/constants.ts <<EOF
          export const constants = {
              url: 'https://codingneko.com',
              misskeyApiUrl: 'https://codingneko.com/api/emojis',
              githubApiUrl: 'https://api.github.com/graphql',
              githubAuthToken: '${{ secrets.GITHUB_TOKEN }}',
              misskeyAuthToken: '${{ secrets.MISSKEY_TOKEN }}',
              misskeyFolderId: '${{ vars.MISSKEY_FOLDER_ID }}'
          };
          EOF
          
      - name: Install dependencies and build
        run: npm i && npm run build

      - name: Install OpenSSH
        run: sudo apt install openssh-client -y
        
      - name: Create private key
        run: mkdir ~/.ssh && echo ${{secrets.SERVER_PRIV_KEY}} >> ~/.ssh/id_rsa
        
      - name: Upload built code to server
        run: scp -r dist root@codingneko.com:/var/www/codingneko.com/
